### PR TITLE
Send reviews mongo db

### PR DESCRIPTION
**Pull request by MasakiShiraishi**
I created a review using "/review" to send the review to MongoDB.  Once the review is completed, it will be rendered to "/sendReview". However, I am unsure if this is the best practice, so I shoud fix it if it isn't suitable for the project.

https://github.com/JrSchoolAccount/Kino-site-nextjs/assets/112933577/e71740cf-de05-44c7-ba2f-f76110d7a7e6

### CODE REVIEW

**Comment by MasakiShiraishi** [comment]
Hello. 
I replaced the address with our MONGODB_URI for the project and it seems to be successful for sending a review to MongoDB.
In my local repository, the .env.local file contains "MONGODB_URI=(usename):(password)@kinodb.swomc4h.mongodb.net/kinoDB?retryWrites=true&w=majority".

**Review by NelsonTheBrave — CHANGES_REQUESTED** [review]
It seems to work like you describe, which is nice! And good work in general :)

I think we shouldn't have the review function as a separate page though, but as a component on each individual movie page. But fair enough, that you can add in a later branch, so that isn't necessarily a reason to not merge this.

However you have used a bit different of a folder structure compared to what we have used so far. I think it would be good to put your model in the existing models.ts file so they are all together there. Also you seem to be handling the post to our database with a server component, while we so far have opted to use api routes instead. I don't know if it's a big problem to combine the two, but I makes the project a bit messy. If you look in main, you see that we have used the system to create a route.ts file for each route, under the api folder. The route.ts contains a function that specifies the method you use to interact with the API, in this case POST.

**Comment by MasakiShiraishi** [comment]
I updated and fixed your recommendation. Additionally, I added a form review to every movie page such as /filmer[id] (/filmer/573a13b5f29313caabd447f5).

Skärmbild_16-5-2024_212113_localhost

**Review by NelsonTheBrave — APPROVED** [review]
Good fixes, now it works the way it should :)

**Review by FelixHultman — APPROVED** [review]

**Pull request merged**
